### ISSUE TITLE
Produce additional release artefact with Shenandoah enabled

### ISSUE THREAD

**Issue by jerboaa** [AdoptOpenJDK/openjdk11-upstream-binaries#11]
The default JDK 11u build won't compile Shenandoah GC into the libjvm.so library. We should produce an additional artefact which comes with Shenandoah GC enabled so that interested parties can get it from our release Github page.

When Shenandoah GC is not available it looks like this:

```
$ java -XX:+UseShenandoahGC -version
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

When Shenandoah GC has been compiled in this looks like:

```
$ java -XX:+UseShenandoahGC -version
openjdk version "11.0.10-internal" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10-internal+0-adhoc.sgehwolf.openjdk-11-dev)
OpenJDK 64-Bit Server VM (build 11.0.10-internal+0-adhoc.sgehwolf.openjdk-11-dev, mixed mode)
```

The relevant configure option to use is:

```
--with-jvm-features=shenandoagc
```

**Comment by jerboaa** [comment]
@jhuttana Please have a look at this when you get a chance. Thanks! Basically, we should do two configurations, one with shenandoah enabled and one without. The resulting artefact (tarball) name should stay as is for the disabled one and have `-shenandoah` in the name when enabled. Similar idea to what we did for JDK 8 and JFR. Thanks!

**Comment by jhuttana** [comment]
Sure @jerboaa . Thanks for letting me know about this. I will create a PR with needed changes.

**Comment by jerboaa** [comment]
@jhuttana Please ensure this gets fixed (i.e. pr rebased/merged) before the initial 11.0.10+1 EA build. Thanks!

**Comment by jhuttana** [comment]
Okay sure

**Comment by marko-asplund** [comment]
I'm a bit confused about whether Shenandoah should be included in OpenJDK v11.0.9 or not 😕 .

According to OpenJDK [wiki](https://wiki.openjdk.java.net/display/shenandoah/Main#Main-JDKSupport) Shenandoah should be in mainline builds:

> In mainline OpenJDK 11u builds since 11.0.9.

But apparently it isn't.

**Comment by jerboaa** [comment]
> I'm a bit confused about whether Shenandoah should be included in OpenJDK v11.0.9 or not confused .
> 
> According to OpenJDK [wiki](https://wiki.openjdk.java.net/display/shenandoah/Main#Main-JDKSupport) Shenandoah should be in mainline builds:
> 
> > In mainline OpenJDK 11u builds since 11.0.9.
> 
> But apparently it isn't.

@marko-asplund There are two angles to Shenandoah GC in 11u. The code itself is indeed included in jdk-updates/jdk11u since 11.0.9. However, the build system of OpenJDK allows one to enable certain features on a per-feature basis (`--with-jvm-features=shenandoahgc` in this case). I.e. there is a mechanism to select features which get compiled into `libjvm.so` **at build time**. When Shenandoah GC got integrated into 11u, the consensus was to have that feature **disabled by default**. What does this mean exactly? If you build from the [jdk-updates/jdk11u](https://hg.openjdk.java.net/jdk-updates/jdk11u) tree yourself and don't add `--with-jvm-features=shenandoahgc` to your `configure` then you'll get a JDK 11 build *without* Shenandoah compiled in. You only get a Shenandoah-enabled JVM if you provide that configure switch explicitly.

With OpenJDK Project Builds we build with **default** configure switches as much as possible. So the resulting binary will not have Shenandoah built in. But we'll produce another JDK artefact download, which has it enabled (this ticket). Stay tuned for the first 11.0.10 EA bits and you can try both.

**Comment by marko-asplund** [comment]
@jerboaa understood - thanks for elaborating! 👍 🙇 

🤔  I'm running an app on the openjdk docker container which probably won't include Shenandoah then.
Or not until 11.0.10 i.e. ~ end of January 2021 anyway.

**Comment by jerboaa** [comment]
> @jerboaa understood - thanks for elaborating! +1 bow
> 
> thinking I'm running an app on the openjdk docker container which probably won't include Shenandoah then.

Probably.

> Or not until 11.0.10 i.e. ~ end of January 2021 anyway.

That'll depend on which build your image vendor consumes for docker images. Without some manual intervention by your docker container vendor somewhere, 11.0.10 builds will also not have Shenandoah.

Let me clarify again, that the **default** will stay with Shenandoah **not** compiled in unless the upstream default changes. There will be a way to manually download an Shenandoah enabled build from the same GH releases page where other binaries are hosted.
