### ISSUE TITLE
After #18 Mandrel no longer builds

### ISSUE THREAD

**Issue by zakkak** [AdoptOpenJDK/openjdk11-upstream-binaries#19]
As described in https://github.com/graalvm/mandrel/issues/210 Mandrel fails to build with the latest EA builds due to the move of static libraries from `lib/static/linux-amd64/glibc/` to `lib/static/linux-amd64/glibc/lib/`.

The said change was made in https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/pull/18

\cc @jerboaa

**Comment by jerboaa** [comment]
That's a bug. it should have stayed as is in:
`lib/static/linux-amd64/glibc/`. #18 meant to remove the empty static-libs folder only!

Thanks for the report, @zakkak

**Comment by jhuttana** [comment]
Okay! I will take a look

**Comment by jerboaa** [comment]
Thanks
