### ISSUE TITLE
Future Home?

### ISSUE THREAD

**Issue by tianon** [AdoptOpenJDK/openjdk11-upstream-binaries#23]
Given https://blog.adoptopenjdk.net/2021/03/transition-to-eclipse-an-update/, are this repository/releases going to move to Adoptium too? :sweat_smile:

**Comment by smlambert** [comment]
No, these repos will stay here, and contents continue to be served up via the AdoptOpenJDK API.  For Adoptium releases, there are new release repositories for the Temurin JDKs at Adoptium (example: https://github.com/adoptium/temurin11-binaries), and to aid the transition will also be served up from the AdoptOpenJDK API for a couple of releases, though we'd encourage people to move to using the Adoptium API as soon as possible.
