### ISSUE TITLE
macOS binaries

### ISSUE THREAD

**Issue by andersonkyle** [AdoptOpenJDK/openjdk11-upstream-binaries#24]
Would it be possible to include binaries for macOS in each release?

**Comment by jerboaa** [comment]
Sorry, there are no plans to do that. I suggest to use binaries from adoptium.net instead.

**Comment by andersonkyle** [comment]
Just out of curiosity, is there any particular reason why macOS binaries won't be included?  Would you accept a PR?

**Comment by jerboaa** [comment]
We don't have the cycles/infrastructure to build them. So it's a function of cost/benefit. While a PR is one step, having the required infra to build them regularly (and test!) is the actual blocker for us right now.

**Comment by andersonkyle** [comment]
That's fair.  I wasn't sure what was involved since these are the upstream binaries.  Thanks for the additional context.
