### ISSUE TITLE
Failed to load instrument dll since Java 11.0.5

### ISSUE THREAD

**Issue by omerb4** [AdoptOpenJDK/openjdk11-upstream-binaries#3]
Hi, I noticed that since upgrade to OpenJDK 11.0.5 I can no longer use the instrument.dll
under the bin folder.
From comparing the dll to previous version I noticed a big difference in the DLL size which is doesn't make any sense.
In 11.0.4 the DLL size is 174KB while in 11.0.5 it's only 39KB.
I also checked the DLL in the official Oracle version of 11.0.5 and it's 174KB.

Any idea what's happens with that file?

**Comment by jerboaa** [comment]
Paging @stooke to investigate.

**Comment by notfred** [comment]
I'll take a look at this now.

**Comment by stooke** [comment]
> Hi, I noticed that since upgrade to OpenJDK 11.0.5 I can no longer use the instrument.dll
> under the bin folder.
> From comparing the dll to previous version I noticed a big difference in the DLL size which is doesn't make any sense.
> In 11.0.4 the DLL size is 174KB while in 11.0.5 it's only 39KB.
> I also checked the DLL in the official Oracle version of 11.0.5 and it's 174KB.
> 
> Any idea what's happens with that file?

I'm taking a look.  Can you post the exact error message? Do you have a small reproducer?  
Also, have you tried replacing the file (save the old one) in 1.0.5 with the 1.0.4 instruments.dll?

**Comment by omerb4** [comment]
Yes, when I used an older instruments.dll file it worked.
There's a tool called API Monitor that I used in order to investigate why my app cannot be started anymore and I noticed that it failed to load the DLL with error (126 = The specified module could not be found).
This caused by a call using by jvm.dll to LoadLibraryA("instrument.dll").
So you can simply do this Win API call yourself and you'll be able to reproduce it on that specific DLL.

![image](https://user-images.githubusercontent.com/15855765/71908322-70683180-3176-11ea-9773-299f7fd42b27.png)

**Comment by stooke** [comment]
The old DLL was statically linked, hence the size difference.
I believe this is caused by the following checkin:
http://hg.openjdk.java.net/jdk/jdk/rev/3f32076a43a6
from this issue: https://bugs.openjdk.java.net/browse/JDK-8210919

I will poke around, and see if it's in later JDKs, too.

**Comment by stooke** [comment]
I am able to load the library from Java code.  Are you sure that the (jdk home)/bin directory is on the execution path for your executable, or in property java.library.path ?

**Comment by omerb4** [comment]
> The old DLL was statically linked, hence the size difference.
> I believe this is caused by the following checkin:
> http://hg.openjdk.java.net/jdk/jdk/rev/3f32076a43a6
> from this issue: https://bugs.openjdk.java.net/browse/JDK-8210919
> 
> I will poke around, and see if it's in later JDKs, too.

**Comment by omerb4** [comment]
> I am able to load the library from Java code. Are you sure that the (jdk home)/bin directory is on the execution path for your executable, or in property java.library.path ?

I'm sure that the bin folder is in the execution path, I can try to reproduce it myself if it's necessary.
When I use java option flag -javaagent: then this error occurs, otherwise everything is ok.

Try use this jar as the agent:
![jar-loader](https://user-images.githubusercontent.com/15855765/71928271-e3d26900-319f-11ea-9dbb-bd22d2fd932a.jpg)
(Change the file extension to jar)

**Comment by stooke** [comment]
Please give a complete example, including command line, java code and exact JDK version (including build number).  It saves a lot of time for both of us, as I can't currently reproduce the issue.

Have you tried adding -Djava.library.path="(jdk home)/bin" to your command line?

**Comment by stooke** [comment]
Using the tool you pointed me to, I can see instrument.dll being loaded and called.  It _may_ be an OS version issue or a path issue, but I can't yet reproduce it.  (jjj.jar is your file)

C:\>openjdk-11.0.5_10\bin\java -javaagent:jjj.jar TestInt
Hello, World
C:\>
![Capture](https://user-images.githubusercontent.com/28760513/71929928-af8f8600-3168-11ea-9d12-e08fbc7d5656.PNG)

**Comment by omerb4** [comment]
I just used a python command line to simulate LoadLibrary and it failed to load both on Windows Server 2008 R2 and on my Windows 10 environment.
I used this JRE: 
https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/download/jdk-11.0.5%2B10/OpenJDK11U-jre_x64_windows_11.0.5_10.zip 

Python code:

> import ctypes
> ctypes.windll.LoadLibrary("instrument.dll")

**Comment by omerb4** [comment]
The problem was the dymanic link to jli.dll that wasn't found in path once instrument.dll was loaded.

Thanks for the help

**Comment by stooke** [comment]
I'm glad that you were able to get going, but I'm curious; why wasn't jli.dll found to begin with?  What did you have to do to fix your issue?  I'm asking in case we can make the error more informative, or document this behaviour.

**Comment by omerb4** [comment]
By default, my application is not adding java bin to the path cause I don't want to modify the machine on the installation.
All the api-ms dll's are provided by installing the Microsoft VC's files so when loading jvm dll they are automatically loaded through System32.

Since 11.0.5 I should add jli.dll to my application bin folder cause this is the only missing DLL that not allowing my application to start.

All I done is copy the jli.dll to another folder so the load of instrument.dll will work for me.

**Comment by stooke** [comment]
Ah, thanks for the explanation.  You may be able to save some future headaches by using "-Djava.library.path=%JAVA_HOME%\bin" (or some variant) on your Java command line.

**Comment by omerb4** [comment]
I use an spring boot application that using Procrun to start, I added to the registry this flag and it didn't help so that's why it confused me.

**Comment by omerb4** [comment]
@stooke I think that the loading a dll is only based on the windows search path logic and that's why the -Djava.library.path argument is not relevant in that case.

Here's the windows dll search path logic:
https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order

WDYT? Is that make sense?
