### ISSUE TITLE
Folder name not the same in the assemblies

### ISSUE THREAD

**Issue by rady66** [AdoptOpenJDK/openjdk11-upstream-binaries#6]
Could we please make the folder name the same? At the moment they are different in the distribution assemblies (zip, tar.gz, etc.), e.g. windows one is "openjdk-11.0.7_10-jre" and linux one is "openjdk-11.0.7+10-jre". That could save work in some DevOps scenarios/scripts.

**Comment by jerboaa** [comment]
OK. Thanks for the report.

Out of curiosity, what's your use-case? As a general note, it doesn't seem a good idea to rely on the folder name in your scripts.

We could potentially change it to something like `openjdk-11.0.7_10-jre` throughout for our upcoming releases.

**Comment by rady66** [comment]
@jerboaa, thanks for your prompt response and committing potential improvement.

The use-case is pretty simple. You know, one releases a tested software against particular JRE version. There might be an install guide, or furthermore, an automated script setup (e.g. Ant build.xml), which could execute in steps (1. download jre and unzip. 2. install/copy/unzip software 3. update java home, path and start software)... and when executing last step instead of having map (jre version->folder), we need to maintain more complex structure - matrix (jre version -> os folders) with the OS names.

I know it is much better to deal with env variables like JAVA_HOME/PATH instead of relying on folder names, but then we just move the same problem to when we update that var.

**Comment by jerboaa** [comment]
@jhuttana Could you please look into this? Let's change the folder name on Linux to be the same as for the Windows version: `openjdk-11.0.7_10-jre` and `openjdk-11.0.7_10` over `openjdk-11.0.7+10-jre` and `openjdk-11.0.7+10`.

**Comment by jhuttana** [comment]
> @jhuttana Could you please look into this? Let's change the folder name on Linux to be the same as for the Windows version: `openjdk-11.0.7_10-jre` and `openjdk-11.0.7_10` over `openjdk-11.0.7+10-jre` and `openjdk-11.0.7+10`.

@jerboaa Sure!

**Comment by jerboaa** [comment]
@jhuttana Thanks!

**Comment by jerboaa** [comment]
Closed with #7

**Comment by jerboaa** [comment]
11.0.8+6 EA build should have the fix.

**Comment by jhuttana** [comment]
> 11.0.8+6 EA build should have the fix.

@jerboaa Sure :)
